# Generated by Django 3.1 on 2020-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_output', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptstext',
            name='large',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acceptstext',
            name='medium',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acceptstext',
            name='small',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
